services:
  django_backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: django_backend
    #volumes:
    #  - ./backend:/app
    #working_dir: /app
    ports:
      - '8000:8000'
    env_file:
      - .env
    environment:
      # Connessione al PostgreSQL esterno sul host 192.168.1.43
      DB_HOST: 192.168.1.43
      DB_PORT: 5432
    depends_on:
      - db
    networks:
      sticky_net:
        ipv4_address: 172.25.0.10

  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      sticky_net:
        ipv4_address: 172.25.0.5

  sticky_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sticky_frontend
    ports:
      - '3000:80'
    depends_on:
      - django_backend
    networks:
      sticky_net:
        ipv4_address: 172.25.0.20

volumes:
  pgdata:

networks:
  sticky_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
