version: '3.8'

services:
  django_backend:
    build:
      context: .
      dockerfile: backend/Dockerfile # <── must point here
    container_name: django_backend
    env_file:
      - .env
    ports:
      - '8000:8000'
    depends_on:
      - postgres_db
    # ← non montare più ./backend:/app

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  sticky_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sticky_frontend
    ports:
      - '3000:80'
    depends_on:
      - django_backend

volumes:
  pgdata:
